workflows:
  android-workflow:
    name: Android Workflow
    # ....
    environment:
      android_signing:
        - voiceassistant

      vars:
        PACKAGE_NAME: 'io.codemagic.sample.reactnative'
scripts:
  # ....
  - name: Install npm dependencies
    script: |
      npm install
  - name: Set Android SDK location
    script: |
      echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
  - name: Build Android release
    script: |
      cd android
      ./gradlew bundleRelease

artifacts:
  - android/app/build/outputs/**/*.aab

environment:
  groups:
    - firebase_credentials
publishing:
  firebase:
    # use this line to authenticate via service account
    firebase_service_account: $FIREBASE_SERVICE_ACCOUNT

    # or this line to authenticate via token:
    # firebase_token: $FIREBASE_TOKEN

    android:
      # Add your Android app id retrieved from Firebase console
      app_id: 1:893539496728:android:c473a6eabc4e0678e8e46d

      # Add one or more groups that you wish to distribute your Android application to.
      # You can create groups in the Firebase console
      groups:
        - yash
      artifact_type: 'apk'
